<form class="wooecom_instant_order" id="wooecom_instant_order">
    <div class="wooecom_instant_order_form">
        <p class="wooecom_notice hidden">قم بإدخال المعلومات ثم إرسال الطلب</p>
        <p class="wooecom_information_title">
            يمكنكم القيام بطلب عبر النموذج التالي أو الإتصال بنا على الرقم 0123456789
        </p>
        <input type="text" name="wooecom_name" id="wooecom_name" placeholder="👦🏻 الاسم الكامل" required="" />
        <input type="tel" name="wooecom_phone" id="wooecom_phone" pattern="[0-9]+" placeholder="رقم الهاتف 📞"
            required="" />
        <select name="wooecom_state" id="wooecom_state" placeholder="🏠 الولاية / المنطقة" required="">
            <option value="">🏠 الولاية / المنطقة</option>
            <option value="DZ-01">01 Adrar - أدرار</option>
            <option value="DZ-02">02 Chlef - الشلف</option>
            <option value="DZ-03">03 Laghouat - الأغواط</option>
            <option value="DZ-04">04 Oum El Bouaghi - أم البواقي</option>
            <option value="DZ-05">05 Batna - باتنة</option>
            <option value="DZ-06">06 Béjaïa - بجاية</option>
            <option value="DZ-07">07 Biskra - بسكرة</option>
            <option value="DZ-08">08 Bechar - بشار</option>
            <option value="DZ-09">09 Blida - البليدة</option>
            <option value="DZ-10">10 Bouira - البويرة</option>
            <option value="DZ-11">11 Tamanrasset - تمنراست</option>
            <option value="DZ-12">12 Tébessa - تبسة</option>
            <option value="DZ-13">13 Tlemcene - تلمسان</option>
            <option value="DZ-14">14 Tiaret - تيارت</option>
            <option value="DZ-15">15 Tizi Ouzou - تيزي وزو</option>
            <option value="DZ-16">16 Alger - الجزائر</option>
            <option value="DZ-17">17 Djelfa - الجلفة</option>
            <option value="DZ-18">18 Jijel - جيجل</option>
            <option value="DZ-19">19 Sétif - سطيف</option>
            <option value="DZ-20">20 Saïda - سعيدة</option>
            <option value="DZ-21">21 Skikda - سكيكدة</option>
            <option value="DZ-22">22 Sidi Bel Abbès - سيدي بلعباس</option>
            <option value="DZ-23">23 Annaba - عنابة</option>
            <option value="DZ-24">24 Guelma - قالمة</option>
            <option value="DZ-25">25 Constantine - قسنطينة</option>
            <option value="DZ-26">26 Médéa - المدية</option>
            <option value="DZ-27">27 Mostaganem - مستغانم</option>
            <option value="DZ-28">28 MSila - مسيلة</option>
            <option value="DZ-29">29 Mascara - معسكر</option>
            <option value="DZ-30">30 Ouargla - ورقلة</option>
            <option value="DZ-31">31 Oran - وهران</option>
            <option value="DZ-32">32 El Bayadh - البيض</option>
            <option value="DZ-33">33 Illizi - إليزي</option>
            <option value="DZ-34">34 Bordj Bou Arreridj - برج بوعريريج</option>
            <option value="DZ-35">35 Boumerdès - بومرداس</option>
            <option value="DZ-36">36 El Tarf - الطارف</option>
            <option value="DZ-37">37 Tindouf - تندوف</option>
            <option value="DZ-38">38 Tissemsilt - تيسمسيلت</option>
            <option value="DZ-39">39 Eloued - الوادي</option>
            <option value="DZ-40">40 Khenchela - خنشلة</option>
            <option value="DZ-41">41 Souk Ahras - سوق أهراس</option>
            <option value="DZ-42">42 Tipaza - تيبازة</option>
            <option value="DZ-43">43 Mila - ميلة</option>
            <option value="DZ-44">44 Aïn Defla - عين الدفلى</option>
            <option value="DZ-45">45 Naâma - النعامة</option>
            <option value="DZ-46">46 Aïn Témouchent - عين تموشنت</option>
            <option value="DZ-47">47 Ghardaïa - غرداية</option>
            <option value="DZ-48">48 Relizane- غليزان</option>
            <option value="DZ-49">49 Timimoun - تيميمون</option>
            <option value="DZ-50">50 Bordj Baji Mokhtar - برج باجي مختار</option>
            <option value="DZ-51">51 Ouled Djellal - أولاد جلال</option>
            <option value="DZ-52">52 Béni Abbès - بني عباس</option>
            <option value="DZ-53">53 Aïn Salah - عين صالح</option>
            <option value="DZ-54">54 In Guezzam - عين قزام</option>
            <option value="DZ-55">55 Touggourt - تقرت</option>
            <option value="DZ-56">56 Djanet - جانت</option>
            <option value="DZ-57">57 El MGhair - المغير</option>
            <option value="DZ-58">58 El Menia - المنيعة</option>
        </select>
        <!-- <select
      name="wooecom_city"
      id="wooecom_city"
      class="select"
      data-placeholder="📍 البلدية"
      required="required"
    >
      <option value="">📍 البلدية</option>
    </select> -->
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                var cities = {
                    "DZ-01": [
                        "Adrar",
                        "Tamest",
                        "Charouine",
                        "Reggane",
                        "Inozghmir",
                        "Tit",
                        "Ksar Kaddour",
                        "Tsabit",
                        "Timimoun",
                        "Ouled Said",
                        "Zaouiet Kounta",
                        "Aoulef",
                        "Timokten",
                        "Tamentit",
                        "Fenoughil",
                        "Tinerkouk",
                        "Deldoul",
                        "Sali",
                        "Akabli",
                        "Metarfa",
                        "O Ahmed Timmi",
                        "Bouda",
                        "Aougrout",
                        "Talmine",
                        "B Badji Mokhtar",
                        "Sbaa",
                        "Ouled Aissa",
                        "Timiaouine",
                    ],
                    "DZ-02": [
                        "Chlef",
                        "Tenes",
                        "Benairia",
                        "El Karimia",
                        "Tadjna",
                        "Taougrite",
                        "Beni Haoua",
                        "Sobha",
                        "Harchoun",
                        "Ouled Fares",
                        "Sidi Akacha",
                        "Boukadir",
                        "Beni Rached",
                        "Talassa",
                        "Herenfa",
                        "Oued Goussine",
                        "Dahra",
                        "Ouled Abbes",
                        "Sendjas",
                        "Zeboudja",
                        "Oued Sly",
                        "Abou El Hassen",
                        "El Marsa",
                        "Chettia",
                        "Sidi Abderrahmane",
                        "Moussadek",
                        "El Hadjadj",
                        "Labiod Medjadja",
                        "Oued Fodda",
                        "Ouled Ben Abdelkader",
                        "Bouzghaia",
                        "Ain Merane",
                        "Oum Drou",
                        "Breira",
                        "Ben Boutaleb",
                    ],
                    "DZ-03": [
                        "Laghouat",
                        "Ksar El Hirane",
                        "Benacer Ben Chohra",
                        "Sidi Makhlouf",
                        "Hassi Delaa",
                        "Hassi R Mel",
                        "Ain Mahdi",
                        "Tadjmout",
                        "Kheneg",
                        "Gueltat Sidi Saad",
                        "Ain Sidi Ali",
                        "Beidha",
                        "Brida",
                        "El Ghicha",
                        "Hadj Mechri",
                        "Sebgag",
                        "Taouiala",
                        "Tadjrouna",
                        "Aflou",
                        "El Assafia",
                        "Oued Morra",
                        "Oued M Zi",
                        "El Haouaita",
                        "Sidi Bouzid",
                    ],
                    "DZ-04": [
                        "Oum El Bouaghi",
                        "Ain Beida",
                        "Ainmlila",
                        "Behir Chergui",
                        "El Amiria",
                        "Sigus",
                        "El Belala",
                        "Ain Babouche",
                        "Berriche",
                        "Ouled Hamla",
                        "Dhala",
                        "Ain Kercha",
                        "Hanchir Toumghani",
                        "El Djazia",
                        "Ain Diss",
                        "Fkirina",
                        "Souk Naamane",
                        "Zorg",
                        "El Fedjoudj Boughrar",
                        "Ouled Zouai",
                        "Bir Chouhada",
                        "Ksar Sbahi",
                        "Oued Nini",
                        "Meskiana",
                        "Ain Fekroune",
                        "Rahia",
                        "Ain Zitoun",
                        "Ouled Gacem",
                        "El Harmilia",
                    ],
                    "DZ-05": [
                        "Batna",
                        "Ghassira",
                        "Maafa",
                        "Merouana",
                        "Seriana",
                        "Menaa",
                        "El Madher",
                        "Tazoult",
                        "Ngaous",
                        "Guigba",
                        "Inoughissen",
                        "Ouyoun El Assafir",
                        "Djerma",
                        "Bitam",
                        "Metkaouak",
                        "Arris",
                        "Kimmel",
                        "Tilatou",
                        "Ain Djasser",
                        "Ouled Selam",
                        "Tigherghar",
                        "Ain Yagout",
                        "Fesdis",
                        "Sefiane",
                        "Rahbat",
                        "Tighanimine",
                        "Lemsane",
                        "Ksar Belezma",
                        "Seggana",
                        "Ichmoul",
                        "Foum Toub",
                        "Beni Foudhala El Hakania",
                        "Oued El Ma",
                        "Talkhamt",
                        "Bouzina",
                        "Chemora",
                        "Oued Chaaba",
                        "Taxlent",
                        "Gosbat",
                        "Ouled Aouf",
                        "Boumagueur",
                        "Barika",
                        "Djezzar",
                        "Tkout",
                        "Ain Touta",
                        "Hidoussa",
                        "Teniet El Abed",
                        "Oued Taga",
                        "Ouled Fadel",
                        "Timgad",
                        "Ras El Aioun",
                        "Chir",
                        "Ouled Si Slimane",
                        "Zanat El Beida",
                        "Amdoukal",
                        "Ouled Ammar",
                        "El Hassi",
                        "Lazrou",
                        "Boumia",
                        "Boulhilat",
                        "Larbaa",
                    ],
                    "DZ-06": [
                        "Bejaia",
                        "Amizour",
                        "Ferraoun",
                        "Taourirt Ighil",
                        "Chelata",
                        "Tamokra",
                        "Timzrit",
                        "Souk El Thenine",
                        "Mcisna",
                        "Thinabdher",
                        "Tichi",
                        "Semaoun",
                        "Kendira",
                        "Tifra",
                        "Ighram",
                        "Amalou",
                        "Ighil Ali",
                        "Ifelain Ilmathen",
                        "Toudja",
                        "Darguina",
                        "Sidi Ayad",
                        "Aokas",
                        "Beni Djellil",
                        "Adekar",
                        "Akbou",
                        "Seddouk",
                        "Tazmalt",
                        "Ait Rizine",
                        "Chemini",
                        "Souk Oufella",
                        "Taskriout",
                        "Tibane",
                        "Tala Hamza",
                        "Barbacha",
                        "Beni Ksila",
                        "Ouzallaguen",
                        "Bouhamza",
                        "Beni Melikeche",
                        "Sidi Aich",
                        "El Kseur",
                        "Melbou",
                        "Akfadou",
                        "Leflaye",
                        "Kherrata",
                        "Draa Kaid",
                        "Tamridjet",
                        "Ait Smail",
                        "Boukhelifa",
                        "Tizi Nberber",
                        "Beni Maouch",
                        "Oued Ghir",
                        "Boudjellil",
                    ],
                    "DZ-07": [
                        "Biskra",
                        "Oumache",
                        "Branis",
                        "Chetma",
                        "Ouled Djellal",
                        "Ras El Miaad",
                        "Besbes",
                        "Sidi Khaled",
                        "Doucen",
                        "Ech Chaiba",
                        "Sidi Okba",
                        "Mchouneche",
                        "El Haouch",
                        "Ain Naga",
                        "Zeribet El Oued",
                        "El Feidh",
                        "El Kantara",
                        "Ain Zaatout",
                        "El Outaya",
                        "Djemorah",
                        "Tolga",
                        "Lioua",
                        "Lichana",
                        "Ourlal",
                        "Mlili",
                        "Foughala",
                        "Bordj Ben Azzouz",
                        "Meziraa",
                        "Bouchagroun",
                        "Mekhadma",
                        "El Ghrous",
                        "El Hadjab",
                        "Khanguet Sidinadji",
                    ],
                    "DZ-08": [
                        "Bechar",
                        "Erg Ferradj",
                        "Ouled Khoudir",
                        "Meridja",
                        "Timoudi",
                        "Lahmar",
                        "Beni Abbes",
                        "Beni Ikhlef",
                        "Mechraa Houari B",
                        "Kenedsa",
                        "Igli",
                        "Tabalbala",
                        "Taghit",
                        "El Ouata",
                        "Boukais",
                        "Mogheul",
                        "Abadla",
                        "Kerzaz",
                        "Ksabi",
                        "Tamtert",
                        "Beni Ounif",
                    ],
                    "DZ-09": [
                        "Blida",
                        "Chebli",
                        "Bouinan",
                        "Oued El Alleug",
                        "Ouled Yaich",
                        "Chrea",
                        "El Affroun",
                        "Chiffa",
                        "Hammam Melouane",
                        "Ben Khlil",
                        "Soumaa",
                        "Mouzaia",
                        "Souhane",
                        "Meftah",
                        "Ouled Selama",
                        "Boufarik",
                        "Larbaa",
                        "Oued Djer",
                        "Beni Tamou",
                        "Bouarfa",
                        "Beni Mered",
                        "Bougara",
                        "Guerrouaou",
                        "Ain Romana",
                        "Djebabra",
                    ],
                    "DZ-10": [
                        "Bouira",
                        "El Asnam",
                        "Guerrouma",
                        "Souk El Khemis",
                        "Kadiria",
                        "Hanif",
                        "Dirah",
                        "Ait Laaziz",
                        "Taghzout",
                        "Raouraoua",
                        "Mezdour",
                        "Haizer",
                        "Lakhdaria",
                        "Maala",
                        "El Hachimia",
                        "Aomar",
                        "Chorfa",
                        "Bordj Oukhriss",
                        "El Adjiba",
                        "El Hakimia",
                        "El Khebouzia",
                        "Ahl El Ksar",
                        "Bouderbala",
                        "Zbarbar",
                        "Ain El Hadjar",
                        "Djebahia",
                        "Aghbalou",
                        "Taguedit",
                        "Ain Turk",
                        "Saharidj",
                        "Dechmia",
                        "Ridane",
                        "Bechloul",
                        "Boukram",
                        "Ain Bessam",
                        "Bir Ghbalou",
                        "Mchedallah",
                        "Sour El Ghozlane",
                        "Maamora",
                        "Ouled Rached",
                        "Ain Laloui",
                        "Hadjera Zerga",
                        "Ath Mansour",
                        "El Mokrani",
                        "Oued El Berdi",
                    ],
                    "DZ-11": [
                        "Tamanghasset",
                        "Abalessa",
                        "In Ghar",
                        "In Guezzam",
                        "Idles",
                        "Tazouk",
                        "Tinzaouatine",
                        "In Salah",
                        "In Amguel",
                        "Foggaret Ezzaouia",
                    ],
                    "DZ-12": [
                        "Tebessa",
                        "Bir El Ater",
                        "Cheria",
                        "Stah Guentis",
                        "El Aouinet",
                        "Lahouidjbet",
                        "Safsaf El Ouesra",
                        "Hammamet",
                        "Negrine",
                        "Bir El Mokadem",
                        "El Kouif",
                        "Morsott",
                        "El Ogla",
                        "Bir Dheheb",
                        "El Ogla El Malha",
                        "Gorriguer",
                        "Bekkaria",
                        "Boukhadra",
                        "Ouenza",
                        "El Ma El Biodh",
                        "Oum Ali",
                        "Thlidjene",
                        "Ain Zerga",
                        "El Meridj",
                        "Boulhaf Dyr",
                        "Bedjene",
                        "El Mazeraa",
                        "Ferkane",
                    ],
                    "DZ-13": [
                        "Tlemcen",
                        "Beni Mester",
                        "Ain Tallout",
                        "Remchi",
                        "El Fehoul",
                        "Sabra",
                        "Ghazaouet",
                        "Souani",
                        "Djebala",
                        "El Gor",
                        "Oued Chouly",
                        "Ain Fezza",
                        "Ouled Mimoun",
                        "Amieur",
                        "Ain Youcef",
                        "Zenata",
                        "Beni Snous",
                        "Bab El Assa",
                        "Dar Yaghmouracene",
                        "Fellaoucene",
                        "Azails",
                        "Sebbaa Chioukh",
                        "Terni Beni Hediel",
                        "Bensekrane",
                        "Ain Nehala",
                        "Hennaya",
                        "Maghnia",
                        "Hammam Boughrara",
                        "Souahlia",
                        "Msirda Fouaga",
                        "Ain Fetah",
                        "El Aricha",
                        "Souk Thlata",
                        "Sidi Abdelli",
                        "Sebdou",
                        "Beni Ouarsous",
                        "Sidi Medjahed",
                        "Beni Boussaid",
                        "Marsa Ben Mhidi",
                        "Nedroma",
                        "Sidi Djillali",
                        "Beni Bahdel",
                        "El Bouihi",
                        "Honaine",
                        "Tianet",
                        "Ouled Riyah",
                        "Bouhlou",
                        "Souk El Khemis",
                        "Ain Ghoraba",
                        "Chetouane",
                        "Mansourah",
                        "Beni Semiel",
                        "Ain Kebira",
                    ],
                    "DZ-14": [
                        "Tiaret",
                        "Medroussa",
                        "Ain Bouchekif",
                        "Sidi Ali Mellal",
                        "Ain Zarit",
                        "Ain Deheb",
                        "Sidi Bakhti",
                        "Medrissa",
                        "Zmalet El Emir Aek",
                        "Madna",
                        "Sebt",
                        "Mellakou",
                        "Dahmouni",
                        "Rahouia",
                        "Mahdia",
                        "Sougueur",
                        "Sidi Abdelghani",
                        "Ain El Hadid",
                        "Ouled Djerad",
                        "Naima",
                        "Meghila",
                        "Guertoufa",
                        "Sidi Hosni",
                        "Djillali Ben Amar",
                        "Sebaine",
                        "Tousnina",
                        "Frenda",
                        "Ain Kermes",
                        "Ksar Chellala",
                        "Rechaiga",
                        "Nadorah",
                        "Tagdemt",
                        "Oued Lilli",
                        "Mechraa Safa",
                        "Hamadia",
                        "Chehaima",
                        "Takhemaret",
                        "Sidi Abderrahmane",
                        "Serghine",
                        "Bougara",
                        "Faidja",
                        "Tidda",
                    ],
                    "DZ-15": [
                        "Tizi Ouzou",
                        "Ain El Hammam",
                        "Akbil",
                        "Freha",
                        "Souamaa",
                        "Mechtrass",
                        "Irdjen",
                        "Timizart",
                        "Makouda",
                        "Draa El Mizan",
                        "Tizi Ghenif",
                        "Bounouh",
                        "Ait Chaffaa",
                        "Frikat",
                        "Beni Aissi",
                        "Beni Zmenzer",
                        "Iferhounene",
                        "Azazga",
                        "Iloula Oumalou",
                        "Yakouren",
                        "Larba Nait Irathen",
                        "Tizi Rached",
                        "Zekri",
                        "Ouaguenoun",
                        "Ain Zaouia",
                        "Mkira",
                        "Ait Yahia",
                        "Ait Mahmoud",
                        "Maatka",
                        "Ait Boumehdi",
                        "Abi Youcef",
                        "Beni Douala",
                        "Illilten",
                        "Bouzguen",
                        "Ait Aggouacha",
                        "Ouadhia",
                        "Azzefoun",
                        "Tigzirt",
                        "Ait Aissa Mimoun",
                        "Boghni",
                        "Ifigha",
                        "Ait Oumalou",
                        "Tirmitine",
                        "Akerrou",
                        "Yatafen",
                        "Beni Ziki",
                        "Draa Ben Khedda",
                        "Ouacif",
                        "Idjeur",
                        "Mekla",
                        "Tizi Nthlata",
                        "Beni Yenni",
                        "Aghrib",
                        "Iflissen",
                        "Boudjima",
                        "Ait Yahia Moussa",
                        "Souk El Thenine",
                        "Ait Khelil",
                        "Sidi Naamane",
                        "Iboudraren",
                        "Aghni Goughran",
                        "Mizrana",
                        "Imsouhal",
                        "Tadmait",
                        "Ait Bouadou",
                        "Assi Youcef",
                        "Ait Toudert",
                    ],
                    "DZ-16": [
                        "Alger Centre",
                        "Sidi Mhamed",
                        "El Madania",
                        "Hamma Anassers",
                        "Bab El Oued",
                        "Bologhine Ibn Ziri",
                        "Casbah",
                        "Oued Koriche",
                        "Bir Mourad Rais",
                        "El Biar",
                        "Bouzareah",
                        "Birkhadem",
                        "El Harrach",
                        "Baraki",
                        "Oued Smar",
                        "Bourouba",
                        "Hussein Dey",
                        "Kouba",
                        "Bachedjerah",
                        "Dar El Beida",
                        "Bab Azzouar",
                        "Ben Aknoun",
                        "Dely Ibrahim",
                        "Bains Romains",
                        "Rais Hamidou",
                        "Djasr Kasentina",
                        "El Mouradia",
                        "Hydra",
                        "Mohammadia",
                        "Bordj El Kiffan",
                        "El Magharia",
                        "Beni Messous",
                        "Les Eucalyptus",
                        "Birtouta",
                        "Tassala El Merdja",
                        "Ouled Chebel",
                        "Sidi Moussa",
                        "Ain Taya",
                        "Bordj El Bahri",
                        "Marsa",
                        "Haraoua",
                        "Rouiba",
                        "Reghaia",
                        "Ain Benian",
                        "Staoueli",
                        "Zeralda",
                        "Mahelma",
                        "Rahmania",
                        "Souidania",
                        "Cheraga",
                        "Ouled Fayet",
                        "El Achour",
                        "Draria",
                        "Douera",
                        "Baba Hassen",
                        "Khracia",
                        "Saoula",
                    ],
                    "DZ-17": [
                        "Djelfa",
                        "Moudjebara",
                        "El Guedid",
                        "Hassi Bahbah",
                        "Ain Maabed",
                        "Sed Rahal",
                        "Feidh El Botma",
                        "Birine",
                        "Bouira Lahdeb",
                        "Zaccar",
                        "El Khemis",
                        "Sidi Baizid",
                        "Mliliha",
                        "El Idrissia",
                        "Douis",
                        "Hassi El Euch",
                        "Messaad",
                        "Guettara",
                        "Sidi Ladjel",
                        "Had Sahary",
                        "Guernini",
                        "Selmana",
                        "Ain Chouhada",
                        "Oum Laadham",
                        "Dar Chouikh",
                        "Charef",
                        "Beni Yacoub",
                        "Zaafrane",
                        "Deldoul",
                        "Ain El Ibel",
                        "Ain Oussera",
                        "Benhar",
                        "Hassi Fedoul",
                        "Amourah",
                        "Ain Fekka",
                        "Tadmit",
                    ],
                    "DZ-18": [
                        "Jijel",
                        "Erraguene",
                        "El Aouana",
                        "Ziamma Mansouriah",
                        "Taher",
                        "Emir Abdelkader",
                        "Chekfa",
                        "Chahna",
                        "El Milia",
                        "Sidi Maarouf",
                        "Settara",
                        "El Ancer",
                        "Sidi Abdelaziz",
                        "Kaous",
                        "Ghebala",
                        "Bouraoui Belhadef",
                        "Djmila",
                        "Selma Benziada",
                        "Boussif Ouled Askeur",
                        "El Kennar Nouchfi",
                        "Ouled Yahia Khadrouch",
                        "Boudria Beni Yadjis",
                        "Kemir Oued Adjoul",
                        "Texena",
                        "Djemaa Beni Habibi",
                        "Bordj Taher",
                        "Ouled Rabah",
                        "Ouadjana",
                    ],
                    "DZ-19": [
                        "Setif",
                        "Ain El Kebira",
                        "Beni Aziz",
                        "Ouled Sidi Ahmed",
                        "Boutaleb",
                        "Ain Roua",
                        "Draa Kebila",
                        "Bir El Arch",
                        "Beni Chebana",
                        "Ouled Tebben",
                        "Hamma",
                        "Maaouia",
                        "Ain Legraj",
                        "Ain Abessa",
                        "Dehamcha",
                        "Babor",
                        "Guidjel",
                        "Ain Lahdjar",
                        "Bousselam",
                        "El Eulma",
                        "Djemila",
                        "Beni Ouartilane",
                        "Rosfa",
                        "Ouled Addouane",
                        "Belaa",
                        "Ain Arnat",
                        "Amoucha",
                        "Ain Oulmane",
                        "Beidha Bordj",
                        "Bouandas",
                        "Bazer Sakhra",
                        "Hammam Essokhna",
                        "Mezloug",
                        "Bir Haddada",
                        "Serdj El Ghoul",
                        "Harbil",
                        "El Ouricia",
                        "Tizi Nbechar",
                        "Salah Bey",
                        "Ain Azal",
                        "Guenzet",
                        "Talaifacene",
                        "Bougaa",
                        "Beni Fouda",
                        "Tachouda",
                        "Beni Mouhli",
                        "Ouled Sabor",
                        "Guellal",
                        "Ain Sebt",
                        "Hammam Guergour",
                        "Ait Naoual Mezada",
                        "Ksar El Abtal",
                        "Beni Hocine",
                        "Ait Tizi",
                        "Maouklane",
                        "Guelta Zerka",
                        "Oued El Barad",
                        "Taya",
                        "El Ouldja",
                        "Tella",
                    ],
                    "DZ-20": [
                        "Saida",
                        "Doui Thabet",
                        "Ain El Hadjar",
                        "Ouled Khaled",
                        "Moulay Larbi",
                        "Youb",
                        "Hounet",
                        "Sidi Amar",
                        "Sidi Boubekeur",
                        "El Hassasna",
                        "Maamora",
                        "Sidi Ahmed",
                        "Ain Sekhouna",
                        "Ouled Brahim",
                        "Tircine",
                        "Ain Soltane",
                    ],
                    "DZ-21": [
                        "Skikda",
                        "Ain Zouit",
                        "El Hadaik",
                        "Azzaba",
                        "Djendel Saadi Mohamed",
                        "Ain Cherchar",
                        "Bekkouche Lakhdar",
                        "Benazouz",
                        "Es Sebt",
                        "Collo",
                        "Beni Zid",
                        "Kerkera",
                        "Ouled Attia",
                        "Oued Zehour",
                        "Zitouna",
                        "El Harrouch",
                        "Zerdazas",
                        "Ouled Hebaba",
                        "Sidi Mezghiche",
                        "Emdjez Edchich",
                        "Beni Oulbane",
                        "Ain Bouziane",
                        "Ramdane Djamel",
                        "Beni Bachir",
                        "Salah Bouchaour",
                        "Tamalous",
                        "Ain Kechra",
                        "Oum Toub",
                        "Bein El Ouiden",
                        "Fil Fila",
                        "Cheraia",
                        "Kanoua",
                        "El Ghedir",
                        "Bouchtata",
                        "Ouldja Boulbalout",
                        "Kheneg Mayoum",
                        "Hamadi Krouma",
                        "El Marsa",
                    ],
                    "DZ-22": [
                        "Sidi Bel Abbes",
                        "Tessala",
                        "Sidi Brahim",
                        "Mostefa Ben Brahim",
                        "Telagh",
                        "Mezaourou",
                        "Boukhanafis",
                        "Sidi Ali Boussidi",
                        "Badredine El Mokrani",
                        "Marhoum",
                        "Tafissour",
                        "Amarnas",
                        "Tilmouni",
                        "Sidi Lahcene",
                        "Ain Thrid",
                        "Makedra",
                        "Tenira",
                        "Moulay Slissen",
                        "El Hacaiba",
                        "Hassi Zehana",
                        "Tabia",
                        "Merine",
                        "Ras El Ma",
                        "Ain Tindamine",
                        "Ain Kada",
                        "Mcid",
                        "Sidi Khaled",
                        "Ain El Berd",
                        "Sfissef",
                        "Ain Adden",
                        "Oued Taourira",
                        "Dhaya",
                        "Zerouala",
                        "Lamtar",
                        "Sidi Chaib",
                        "Sidi Dahou Dezairs",
                        "Oued Sbaa",
                        "Boudjebaa El Bordj",
                        "Sehala Thaoura",
                        "Sidi Yacoub",
                        "Sidi Hamadouche",
                        "Belarbi",
                        "Oued Sefioun",
                        "Teghalimet",
                        "Ben Badis",
                        "Sidi Ali Benyoub",
                        "Chetouane Belaila",
                        "Bir El Hammam",
                        "Taoudmout",
                        "Redjem Demouche",
                        "Benachiba Chelia",
                        "Hassi Dahou",
                    ],
                    "DZ-23": [
                        "Annaba",
                        "Berrahel",
                        "El Hadjar",
                        "Eulma",
                        "El Bouni",
                        "Oued El Aneb",
                        "Cheurfa",
                        "Seraidi",
                        "Ain Berda",
                        "Chetaibi",
                        "Sidi Amer",
                        "Treat",
                    ],
                    "DZ-24": [
                        "Guelma",
                        "Nechmaya",
                        "Bouati Mahmoud",
                        "Oued Zenati",
                        "Tamlouka",
                        "Oued Fragha",
                        "Ain Sandel",
                        "Ras El Agba",
                        "Dahouara",
                        "Belkhir",
                        "Ben Djarah",
                        "Bou Hamdane",
                        "Ain Makhlouf",
                        "Ain Ben Beida",
                        "Khezara",
                        "Beni Mezline",
                        "Bou Hachana",
                        "Guelaat Bou Sbaa",
                        "Hammam Maskhoutine",
                        "El Fedjoudj",
                        "Bordj Sabat",
                        "Hamman Nbail",
                        "Ain Larbi",
                        "Medjez Amar",
                        "Bouchegouf",
                        "Heliopolis",
                        "Ain Hessania",
                        "Roknia",
                        "Salaoua Announa",
                        "Medjez Sfa",
                        "Boumahra Ahmed",
                        "Ain Reggada",
                        "Oued Cheham",
                        "Djeballah Khemissi",
                    ],
                    "DZ-25": [
                        "Constantine",
                        "Hamma Bouziane",
                        "El Haria",
                        "Zighoud Youcef",
                        "Didouche Mourad",
                        "El Khroub",
                        "Ain Abid",
                        "Beni Hamiden",
                        "Ouled Rahmoune",
                        "Ain Smara",
                        "Mesaoud Boudjeriou",
                        "Ibn Ziad",
                    ],
                    "DZ-26": [
                        "Medea",
                        "Ouzera",
                        "Ouled Maaref",
                        "Ain Boucif",
                        "Aissaouia",
                        "Ouled Deide",
                        "El Omaria",
                        "Derrag",
                        "El Guelbelkebir",
                        "Bouaiche",
                        "Mezerena",
                        "Ouled Brahim",
                        "Damiat",
                        "Sidi Ziane",
                        "Tamesguida",
                        "El Hamdania",
                        "Kef Lakhdar",
                        "Chelalet El Adhaoura",
                        "Bouskene",
                        "Rebaia",
                        "Bouchrahil",
                        "Ouled Hellal",
                        "Tafraout",
                        "Baata",
                        "Boghar",
                        "Sidi Naamane",
                        "Ouled Bouachra",
                        "Sidi Zahar",
                        "Oued Harbil",
                        "Benchicao",
                        "Sidi Damed",
                        "Aziz",
                        "Souagui",
                        "Zoubiria",
                        "Ksar El Boukhari",
                        "El Azizia",
                        "Djouab",
                        "Chahbounia",
                        "Meghraoua",
                        "Cheniguel",
                        "Ain Ouksir",
                        "Oum El Djalil",
                        "Ouamri",
                        "Si Mahdjoub",
                        "Tlatet Eddoair",
                        "Beni Slimane",
                        "Berrouaghia",
                        "Seghouane",
                        "Meftaha",
                        "Mihoub",
                        "Boughezoul",
                        "Tablat",
                        "Deux Bassins",
                        "Draa Essamar",
                        "Sidi Errabia",
                        "Bir Ben Laabed",
                        "El Ouinet",
                        "Ouled Antar",
                        "Bouaichoune",
                        "Hannacha",
                        "Sedraia",
                        "Medjebar",
                        "Khams Djouamaa",
                        "Saneg",
                    ],
                    "DZ-27": [
                        "Mostaganem",
                        "Sayada",
                        "Fornaka",
                        "Stidia",
                        "Ain Nouissy",
                        "Hassi Maameche",
                        "Ain Tadles",
                        "Sour",
                        "Oued El Kheir",
                        "Sidi Bellater",
                        "Kheiredine ",
                        "Sidi Ali",
                        "Abdelmalek Ramdane",
                        "Hadjadj",
                        "Nekmaria",
                        "Sidi Lakhdar",
                        "Achaacha",
                        "Khadra",
                        "Bouguirat",
                        "Sirat",
                        "Ain Sidi Cherif",
                        "Mesra",
                        "Mansourah",
                        "Souaflia",
                        "Ouled Boughalem",
                        "Ouled Maallah",
                        "Mezghrane",
                        "Ain Boudinar",
                        "Tazgait",
                        "Safsaf",
                        "Touahria",
                        "El Hassiane",
                    ],
                    "DZ-28": [
                        "Msila",
                        "Maadid",
                        "Hammam Dhalaa",
                        "Ouled Derradj",
                        "Tarmount",
                        "Mtarfa",
                        "Khoubana",
                        "Mcif",
                        "Chellal",
                        "Ouled Madhi",
                        "Magra",
                        "Berhoum",
                        "Ain Khadra",
                        "Ouled Addi Guebala",
                        "Belaiba",
                        "Sidi Aissa",
                        "Ain El Hadjel",
                        "Sidi Hadjeres",
                        "Ouanougha",
                        "Bou Saada",
                        "Ouled Sidi Brahim",
                        "Sidi Ameur",
                        "Tamsa",
                        "Ben Srour",
                        "Ouled Slimane",
                        "El Houamed",
                        "El Hamel",
                        "Ouled Mansour",
                        "Maarif",
                        "Dehahna",
                        "Bouti Sayah",
                        "Khettouti Sed Djir",
                        "Zarzour",
                        "Oued Chair",
                        "Benzouh",
                        "Bir Foda",
                        "Ain Fares",
                        "Sidi Mhamed",
                        "Ouled Atia",
                        "Souamaa",
                        "Ain El Melh",
                        "Medjedel",
                        "Slim",
                        "Ain Errich",
                        "Beni Ilmane",
                        "Oultene",
                        "Djebel Messaad",
                    ],
                    "DZ-29": [
                        "Mascara",
                        "Bou Hanifia",
                        "Tizi",
                        "Hacine",
                        "Maoussa",
                        "Teghennif",
                        "El Hachem",
                        "Sidi Kada",
                        "Zelmata",
                        "Oued El Abtal",
                        "Ain Ferah",
                        "Ghriss",
                        "Froha",
                        "Matemore",
                        "Makdha",
                        "Sidi Boussaid",
                        "El Bordj",
                        "Ain Fekan",
                        "Benian",
                        "Khalouia",
                        "El Menaouer",
                        "Oued Taria",
                        "Aouf",
                        "Ain Fares",
                        "Ain Frass",
                        "Sig",
                        "Oggaz",
                        "Alaimia",
                        "El Gaada",
                        "Zahana",
                        "Mohammadia",
                        "Sidi Abdelmoumene",
                        "Ferraguig",
                        "El Ghomri",
                        "Sedjerara",
                        "Moctadouz",
                        "Bou Henni",
                        "Guettena",
                        "El Mamounia",
                        "El Keurt",
                        "Gharrous",
                        "Gherdjoum",
                        "Chorfa",
                        "Ras Ain Amirouche",
                        "Nesmot",
                        "Sidi Abdeldjebar",
                        "Sehailia",
                    ],
                    "DZ-30": [
                        "Ouargla",
                        "Ain Beida",
                        "Ngoussa",
                        "Hassi Messaoud",
                        "Rouissat",
                        "Balidat Ameur",
                        "Tebesbest",
                        "Nezla",
                        "Zaouia El Abidia",
                        "Sidi Slimane",
                        "Sidi Khouiled",
                        "Hassi Ben Abdellah",
                        "Touggourt",
                        "El Hadjira",
                        "Taibet",
                        "Tamacine",
                        "Benaceur",
                        "Mnaguer",
                        "Megarine",
                        "El Allia",
                        "El Borma",
                    ],
                    "DZ-31": [
                        "Oran",
                        "Gdyel",
                        "Bir El Djir",
                        "Hassi Bounif",
                        "Es Senia",
                        "Arzew",
                        "Bethioua",
                        "Marsat El Hadjadj",
                        "Ain Turk",
                        "El Ancar",
                        "Oued Tlelat",
                        "Tafraoui",
                        "Sidi Chami",
                        "Boufatis",
                        "Mers El Kebir",
                        "Bousfer",
                        "El Karma",
                        "El Braya",
                        "Hassi Ben Okba",
                        "Ben Freha",
                        "Hassi Mefsoukh",
                        "Sidi Ben Yabka",
                        "Messerghin",
                        "Boutlelis",
                        "Ain Kerma",
                        "Ain Biya",
                    ],
                    "DZ-32": [
                        "El Bayadh",
                        "Rogassa",
                        "Stitten",
                        "Brezina",
                        "Ghassoul",
                        "Boualem",
                        "El Abiodh Sidi Cheikh",
                        "Ain El Orak",
                        "Arbaouat",
                        "Bougtoub",
                        "El Kheither",
                        "Kef El Ahmar",
                        "Boussemghoun",
                        "Chellala",
                        "Krakda",
                        "El Bnoud",
                        "Cheguig",
                        "Sidi Ameur",
                        "El Mehara",
                        "Tousmouline",
                        "Sidi Slimane",
                        "Sidi Tifour",
                    ],
                    "DZ-33": [
                        "Illizi",
                        "Djanet",
                        "Debdeb",
                        "Bordj Omar Driss",
                        "Bordj El Haouasse",
                        "In Amenas",
                    ],
                    "DZ-34": [
                        "Bordj Bou Arreridj",
                        "Ras El Oued",
                        "Bordj Zemoura",
                        "Mansoura",
                        "El Mhir",
                        "Ben Daoud",
                        "El Achir",
                        "Ain Taghrout",
                        "Bordj Ghdir",
                        "Sidi Embarek",
                        "El Hamadia",
                        "Belimour",
                        "Medjana",
                        "Teniet En Nasr",
                        "Djaafra",
                        "El Main",
                        "Ouled Brahem",
                        "Ouled Dahmane",
                        "Hasnaoua",
                        "Khelil",
                        "Taglait",
                        "Ksour",
                        "Ouled Sidi Brahim",
                        "Tafreg",
                        "Colla",
                        "Tixter",
                        "El Ach",
                        "El Anseur",
                        "Tesmart",
                        "Ain Tesra",
                        "Bir Kasdali",
                        "Ghilassa",
                        "Rabta",
                        "Haraza",
                    ],
                    "DZ-35": [
                        "Boumerdes",
                        "Boudouaou",
                        "Afir",
                        "Bordj Menaiel",
                        "Baghlia",
                        "Sidi Daoud",
                        "Naciria",
                        "Djinet",
                        "Isser",
                        "Zemmouri",
                        "Si Mustapha",
                        "Tidjelabine",
                        "Chabet El Ameur",
                        "Thenia",
                        "Timezrit",
                        "Corso",
                        "Ouled Moussa",
                        "Larbatache",
                        "Bouzegza Keddara",
                        "Taourga",
                        "Ouled Aissa",
                        "Ben Choud",
                        "Dellys",
                        "Ammal",
                        "Beni Amrane",
                        "Souk El Had",
                        "Boudouaou El Bahri",
                        "Ouled Hedadj",
                        "Laghata",
                        "Hammedi",
                        "Khemis El Khechna",
                        "El Kharrouba",
                    ],
                    "DZ-36": [
                        "El Tarf",
                        "Bouhadjar",
                        "Ben Mhidi",
                        "Bougous",
                        "El Kala",
                        "Ain El Assel",
                        "El Aioun",
                        "Bouteldja",
                        "Souarekh",
                        "Berrihane",
                        "Lac Des Oiseaux",
                        "Chefia",
                        "Drean",
                        "Chihani",
                        "Chebaita Mokhtar",
                        "Besbes",
                        "Asfour",
                        "Echatt",
                        "Zerizer",
                        "Zitouna",
                        "Ain Kerma",
                        "Oued Zitoun",
                        "Hammam Beni Salah",
                        "Raml Souk",
                    ],
                    "DZ-37": ["Tindouf", "Oum El Assel"],
                    "DZ-38": [
                        "Tissemsilt",
                        "Bordj Bou Naama",
                        "Theniet El Had",
                        "Lazharia",
                        "Beni Chaib",
                        "Lardjem",
                        "Melaab",
                        "Sidi Lantri",
                        "Bordj El Emir Abdelkader",
                        "Layoune",
                        "Khemisti",
                        "Ouled Bessem",
                        "Ammari",
                        "Youssoufia",
                        "Sidi Boutouchent",
                        "Larbaa",
                        "Maasem",
                        "Sidi Abed",
                        "Tamalaht",
                        "Sidi Slimane",
                        "Boucaid",
                        "Beni Lahcene",
                    ],
                    "DZ-39": [
                        "El Oued",
                        "Robbah",
                        "Oued El Alenda",
                        "Bayadha",
                        "Nakhla",
                        "Guemar",
                        "Kouinine",
                        "Reguiba",
                        "Hamraia",
                        "Taghzout",
                        "Debila",
                        "Hassani Abdelkrim",
                        "Hassi Khelifa",
                        "Taleb Larbi",
                        "Douar El Ma",
                        "Sidi Aoun",
                        "Trifaoui",
                        "Magrane",
                        "Beni Guecha",
                        "Ourmas",
                        "Still",
                        "Mrara",
                        "Sidi Khellil",
                        "Tendla",
                        "El Ogla",
                        "Mih Ouansa",
                        "El Mghair",
                        "Djamaa",
                        "Oum Touyour",
                        "Sidi Amrane",
                    ],
                    "DZ-40": [
                        "Khenchela",
                        "Mtoussa",
                        "Kais",
                        "Baghai",
                        "El Hamma",
                        "Ain Touila",
                        "Taouzianat",
                        "Bouhmama",
                        "El Oueldja",
                        "Remila",
                        "Cherchar",
                        "Djellal",
                        "Babar",
                        "Tamza",
                        "Ensigha",
                        "Ouled Rechache",
                        "El Mahmal",
                        "Msara",
                        "Yabous",
                        "Khirane",
                        "Chelia",
                    ],
                    "DZ-41": [
                        "Souk Ahras",
                        "Sedrata",
                        "Hanancha",
                        "Mechroha",
                        "Ouled Driss",
                        "Tiffech",
                        "Zaarouria",
                        "Taoura",
                        "Drea",
                        "Haddada",
                        "Khedara",
                        "Merahna",
                        "Ouled Moumen",
                        "Bir Bouhouche",
                        "Mdaourouche",
                        "Oum El Adhaim",
                        "Ain Zana",
                        "Ain Soltane",
                        "Quillen",
                        "Sidi Fredj",
                        "Safel El Ouiden",
                        "Ragouba",
                        "Khemissa",
                        "Oued Keberit",
                        "Terraguelt",
                        "Zouabi",
                    ],
                    "DZ-42": [
                        "Tipaza",
                        "Menaceur",
                        "Larhat",
                        "Douaouda",
                        "Bourkika",
                        "Khemisti",
                        "Aghabal",
                        "Hadjout",
                        "Sidi Amar",
                        "Gouraya",
                        "Nodor",
                        "Chaiba",
                        "Ain Tagourait",
                        "Cherchel",
                        "Damous",
                        "Meurad",
                        "Fouka",
                        "Bou Ismail",
                        "Ahmer El Ain",
                        "Bou Haroun",
                        "Sidi Ghiles",
                        "Messelmoun",
                        "Sidi Rached",
                        "Kolea",
                        "Attatba",
                        "Sidi Semiane",
                        "Beni Milleuk",
                        "Hadjerat Ennous",
                    ],
                    "DZ-43": [
                        "Mila",
                        "Ferdjioua",
                        "Chelghoum Laid",
                        "Oued Athmenia",
                        "Ain Mellouk",
                        "Telerghma",
                        "Oued Seguen",
                        "Tadjenanet",
                        "Benyahia Abderrahmane",
                        "Oued Endja",
                        "Ahmed Rachedi",
                        "Ouled Khalouf",
                        "Tiberguent",
                        "Bouhatem",
                        "Rouached",
                        "Tessala Lamatai",
                        "Grarem Gouga",
                        "Sidi Merouane",
                        "Tassadane Haddada",
                        "Derradji Bousselah",
                        "Minar Zarza",
                        "Amira Arras",
                        "Terrai Bainen",
                        "Hamala",
                        "Ain Tine",
                        "El Mechira",
                        "Sidi Khelifa",
                        "Zeghaia",
                        "Elayadi Barbes",
                        "Ain Beida Harriche",
                        "Yahia Beniguecha",
                        "Chigara",
                    ],
                    "DZ-44": [
                        "Ain Defla",
                        "Miliana",
                        "Boumedfaa",
                        "Khemis Miliana",
                        "Hammam Righa",
                        "Arib",
                        "Djelida",
                        "El Amra",
                        "Bourached",
                        "El Attaf",
                        "El Abadia",
                        "Djendel",
                        "Oued Chorfa",
                        "Ain Lechiakh",
                        "Oued Djemaa",
                        "Rouina",
                        "Zeddine",
                        "El Hassania",
                        "Bir Ouled Khelifa",
                        "Ain Soltane",
                        "Tarik Ibn Ziad",
                        "Bordj Emir Khaled",
                        "Ain Torki",
                        "Sidi Lakhdar",
                        "Ben Allal",
                        "Ain Benian",
                        "Hoceinia",
                        "Barbouche",
                        "Djemaa Ouled Chikh",
                        "Mekhatria",
                        "Bathia",
                        "Tachta Zegagha",
                        "Ain Bouyahia",
                        "El Maine",
                        "Tiberkanine",
                        "Belaas",
                    ],
                    "DZ-45": [
                        "Naama",
                        "Mechria",
                        "Ain Sefra",
                        "Tiout",
                        "Sfissifa",
                        "Moghrar",
                        "Assela",
                        "Djeniane Bourzeg",
                        "Ain Ben Khelil",
                        "Makman Ben Amer",
                        "Kasdir",
                        "El Biod",
                    ],
                    "DZ-46": [
                        "Ain Temouchent",
                        "Chaabet El Ham",
                        "Ain Kihal",
                        "Hammam Bouhadjar",
                        "Bou Zedjar",
                        "Oued Berkeche",
                        "Aghlal",
                        "Terga",
                        "Ain El Arbaa",
                        "Tamzoura",
                        "Chentouf",
                        "Sidi Ben Adda",
                        "Aoubellil",
                        "El Malah",
                        "Sidi Boumediene",
                        "Oued Sabah",
                        "Ouled Boudjemaa",
                        "Ain Tolba",
                        "El Amria",
                        "Hassi El Ghella",
                        "Hassasna",
                        "Ouled Kihal",
                        "Beni Saf",
                        "Sidi Safi",
                        "Oulhaca El Gheraba",
                        "Tadmaya",
                        "El Emir Abdelkader",
                        "El Messaid",
                    ],
                    "DZ-47": [
                        "Ghardaia",
                        "El Meniaa",
                        "Dhayet Bendhahoua",
                        "Berriane",
                        "Metlili",
                        "El Guerrara",
                        "El Atteuf",
                        "Zelfana",
                        "Sebseb",
                        "Bounoura",
                        "Hassi Fehal",
                        "Hassi Gara",
                        "Mansoura",
                    ],
                    "DZ-48": [
                        "Relizane",
                        "Oued Rhiou",
                        "Belaassel Bouzegza",
                        "Sidi Saada",
                        "Ouled Aiche",
                        "Sidi Lazreg",
                        "El Hamadna",
                        "Sidi Mhamed Ben Ali",
                        "Mediouna",
                        "Sidi Khettab",
                        "Ammi Moussa",
                        "Zemmoura",
                        "Beni Dergoun",
                        "Djidiouia",
                        "El Guettar",
                        "Hamri",
                        "El Matmar",
                        "Sidi Mhamed Ben Aouda",
                        "Ain Tarek",
                        "Oued Essalem",
                        "Ouarizane",
                        "Mazouna",
                        "Kalaa",
                        "Ain Rahma",
                        "Yellel",
                        "Oued El Djemaa",
                        "Ramka",
                        "Mendes",
                        "Lahlef",
                        "Beni Zentis",
                        "Souk El Haad",
                        "Dar Ben Abdellah",
                        "El Hassi",
                        "Had Echkalla",
                        "Bendaoud",
                        "El Ouldja",
                        "Merdja Sidi Abed",
                        "Ouled Sidi Mihoub",
                    ],
                    "DZ-49": [
                        "Timimoun",
                        "Charouine",
                        "Ksar Kaddour",
                        "Ouled Said",
                        "Tinerkouk",
                        "Deldoul",
                        "Metarfa",
                        "Aougrout",
                        "Talmine",
                        "Ouled Aissa",
                    ],
                    "DZ-50": ["B Badji Mokhtar", "Timiaouine"],
                    "DZ-51": [
                        "Ouled Djellal",
                        "Sidi Khaled",
                        "Ras El Miad",
                        "Besbes",
                        "Chaiba",
                        "Doucen",
                    ],
                    "DZ-52": [
                        "Beni Abbes",
                        "Tamtert",
                        "Kerzaz",
                        "Timoudi",
                        "Beni Ikhlef",
                        "El Ouata",
                        "Tabelbala",
                        "Ouled Khoudir",
                        "Ksabi",
                        "Igli",
                    ],
                    "DZ-53": ["In Salah", "In Ghar", "Foggaret Azzaouia"],
                    "DZ-54": ["In Guezzam", "Tinzaouatine"],
                    "DZ-55": [
                        "Touggourt",
                        "Nezla",
                        "Tebesbest",
                        "Zaouia El Abidia",
                        "Temacine",
                        "Blidet Amor",
                        "Megarine",
                        "Mnaguer",
                        "Taibet",
                        "Benaceur",
                        "Sidi Slimane",
                        "El-hadjira",
                        "El Alia",
                    ],
                    "DZ-56": ["Djanet", "Bordj El Haouasse"],
                    "DZ-57": [
                        "El-mghair",
                        "Oum Touyour",
                        "Still",
                        "Sidi Khelil",
                        "Djamaa",
                        "Sidi Amrane",
                        "Tenedla",
                        "Mrara",
                    ],
                    "DZ-58": ["El Meniaa", "Hassi Gara", "Hassi Fehal"],
                };
                var placeholder = "📍 البلدية";
                var city_field_template =
                    '<select name="wooecom_city" id="wooecom_city" class="select " data-placeholder="' +
                    placeholder +
                    '" required="required"><option value="">' +
                    placeholder +
                    "</option>";

                function createCityField(options) {
                    return city_field_template + options + "</select>";
                }

                function updateCityField(states) {
                    var city_options = "";
                    $.each(cities[states], function (city_id, city_name) {
                        city_options +=
                            '<option value="' + city_name + '">' + city_name + "</option>";
                    });

                    // Remove the existing city field
                    $("#wooecom_city").remove();

                    // Add the new city field to the form
                    var city_field =
                        city_options.length > 1
                            ? createCityField(city_options)
                            : createCityField("");
                    $("#wooecom_state").after(city_field);
                }

                // Initial city field
                $("#wooecom_state").after(createCityField(""));

                // Update city field on state change
                $("select#wooecom_state").change(function () {
                    updateCityField($(this).val());
                });
            });
        </script>
        <div class="wooecom_placeholder"></div>
        <div class="wooecom_quantity">
            <span class="wooecom_minus"><i class="fa-solid fa-minus"></i></span>
            <input type="number" value="1" min="1" name="wooecom_qty" id="wooecom_qty" required="" readonly="" />
            <span class="wooecom_plus"><i class="fa-solid fa-plus"></i></span>
        </div>
        <button type="submit" class="wooecom_checkout" id="wcqof-place-order-btn">
            <span><?php echo get_option('wcqof_place_order_text', 'اطلب الان'); ?></span>
            <span class="wooecom_btn_loader"></span>
        </button>

        <!-- Order summary -->
    </div>
    <input type="hidden" name="product_id" value="<?php echo get_the_ID(); ?>">
    <div class="wooecom_order_summary active">
        <div class="wooecom_order_summary_head">
            <div class="wooecom_order_summary_title">
                <i class="fa-solid fa-cart-shopping"></i>
                <span>ملخص الطلب</span>
            </div>
            <i class="fa-solid fa-chevron-down"></i>
        </div>

        <div class="wooecom_price_table">
            <div class="order_loader_container">
                <span class="wooecom_order_loader"></span>
            </div>

            <table>
                <tbody>
                    <!-- Product Name -->
                    <tr>
                        <td class="product_name"><?php echo get_the_title(); ?></td>
                        <td class="product_price">
                            <span class="wooecom_order_qty">x<span id="wooecom_qty_display">1</span></span>
                            <span class="wooecom_price">د.ج <span
                                    id="wooecom_product_price"><?php echo wc_get_product(get_the_ID())->get_price(); ?></span></span>
                            <input type="hidden" id="wooecom_price"
                                value="<?php echo wc_get_product(get_the_ID())->get_price(); ?>" />
                        </td>
                    </tr>

                    <!-- Shipping -->
                    <tr>
                        <td>سعر الشحن
                            <div class="wooecom_shipping_prices">
                                <ul class="wooecom_shipping_methods">
                                    <li>
                                        <select id="wooecom_shipping" name="wooecom_shipping">
                                            <option value="0">اختر المنطقة</option>
                                            <option value="200">منطقة 1 - د.ج 200</option>
                                            <option value="300">منطقة 2 - د.ج 300</option>
                                            <option value="500">منطقة 3 - د.ج 500</option>
                                        </select>
                                    </li>
                                </ul>
                            </div>
                        </td>
                        <td class="shipping_price">د.ج <span id="wooecom_shipping_price">0</span></td>
                    </tr>
                    <!-- Total Price -->
                    <tr class="wooecom_row_total_price">
                        <td>السعر الإجمالي</td>
                        <td class="total_price">
                            <span class="wooecom_price">د.ج <span
                                    id="wooecom_total_price"><?php echo wc_get_product(get_the_ID())->get_price(); ?></span></span>
                            <input type="hidden" id="wooecom_total_price_input"
                                value="<?php echo wc_get_product(get_the_ID())->get_price(); ?>" />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <input type="hidden" id="wooecom_total_price_input" name="wooecom_total_price"
        value="<?php echo wc_get_product(get_the_ID())->get_price(); ?>" />

</form>

<!-- Order Summary -->
<!-- <div id="wcqof-order-summary">
    <h3>Order Summary</h3>
    <p>Product Price: <span id="wcqof-product-price"><?php echo wc_get_product(get_the_ID())->get_price(); ?></span>
        <?php echo get_woocommerce_currency_symbol(); ?></p>
    <p>Quantity: <span id="wcqof-quantity-display">1</span></p>
    <p><strong>Total: <span id="wcqof-total-price"></span> <?php echo get_woocommerce_currency_symbol(); ?></strong></p>
</div>

<div class="wooecom_sticky_footer">
    <a href="#wooecom_instant_order" class="wooecom_buy_now">اشتري الان</a>
    <div class="wooecom_footer_icons">
        <a href="tel:+213561571407" class="href">
            <i class="fa-solid fa-phone"></i>
        </a>
        <a target="_blank" href="https://wa.me/+213561571407" class="href">
            <i class="fa-brands fa-whatsapp"></i>
        </a>
    </div>
</div> -->